export const dummyData = [
  {
    ad_desc: "learn what you want...",
    ad_level: "intermediate",
    ad_price: "$52",
    ad_title: "Unlock Your Coding Potential",
    average_rating: "2.07",
    country: "NR",
    first_class: true,
    number_reviews: "1",
    subject: "programming",
    tu_desc:
      "Experienced in online tutoring, providing engaging and interactive learning experiences.",
    tu_hourly: "$29",
    tu_id: 1,
    tu_lastname: "Davis",
    tu_name: "Matthew",
    tu_skill: ["Creative writing", "Digital marketing"],
    subject_names: ['la'],
    subject_levels: [['any'],['any']]
  },
  {
    ad_desc: "learn what you want...",
    ad_level: "intermediate",
    ad_price: "$52",
    ad_title: "Unlock Your Coding Potential",
    average_rating: "2.07",
    country: "NR",
    first_class: true,
    number_reviews: "1",
    subject: "programming",
    tu_desc:
      "Experienced in online tutoring, providing engaging and interactive learning experiences.",
    tu_hourly: "$29",
    tu_id: 2,
    tu_lastname: "Davis",
    tu_name: "Matthew",
    tu_skill: ["Creative writing", "Digital marketing"],
    subject_names: ['le'],
    subject_levels: [['any'],['any']]
  },
  {
    ad_desc: "learn what you want...",
    ad_level: "intermediate",
    ad_price: "$52",
    ad_title: "Unlock Your Coding Potential",
    average_rating: "2.07",
    country: "NR",
    first_class: true,
    number_reviews: "1",
    subject: "programming",
    tu_desc:
      "Experienced in online tutoring, providing engaging and interactive learning experiences.",
    tu_hourly: "$29",
    tu_id: 3,
    tu_lastname: "Davis",
    tu_name: "Matthew",
    tu_skill: ["Creative writing", "Digital marketing"],
    subject_names: ['li'],
    subject_levels: [['any'],['any']]
  },
  {
    ad_desc: "learn what you want...",
    ad_level: "intermediate",
    ad_price: "$52",
    ad_title: "Unlock Your Coding Potential",
    average_rating: "2.07",
    country: "NR",
    first_class: true,
    number_reviews: "1",
    subject: "programming",
    tu_desc:
      "Experienced in online tutoring, providing engaging and interactive learning experiences.",
    tu_hourly: "$29",
    tu_id: 4,
    tu_lastname: "Davis",
    tu_name: "Matthew",
    tu_skill: ["Creative writing", "Digital marketing"],
    subject_names: ['loi'],
    subject_levels: [['any'],['any']]
  },
];
