import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <header className="relative">
          <div
            id="header-container"
            className="px-[135px] pt-[34px] flex items-center justify-between text-white"
          >
            <div className="flex items-center gap-5">
              <div id="logo">
                <h1 className="text-4xl font-black">ClassPro</h1>
              </div>
              <nav>
                <ul className="flex before:content-['|'] text-xl gap-10">
                  <li>
                    <Link href={"#"}>Find Tutors</Link>
                  </li>
                  <li>
                    <Link href={"#"}>Became a Tutor</Link>
                  </li>
                  <li>
                    <Link href={"#"}>Blog</Link>
                  </li>
                  <li>
                    <Link href={"#"}>Resources</Link>
                  </li>
                </ul>
              </nav>
            </div>
            <div className="flex items-center text-xl font-bold gap-8">
              <Link href={"#"} className="text-black">Login</Link>
              <Link href={"#"} className="bg-main rounded-lg text-white px-5 py-2">
                Sign up
              </Link>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
